### ISSUE TITLE
spectral_cube dependency not installed with pip [BUG]

### ISSUE THREAD

**Issue by HeloiseS** [Deech08/whampy#12]
## Issue

I was playing with  the last part of the [Interactive Map tutorial](https://whampy.readthedocs.io/en/latest/click_maps.html) and got this error:
```
>>> click_map = survey.click_map(fig = fig, over_data = fits_cube_path)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fste075/anaconda3/envs/whampy_test/lib/python3.7/site-packages/whampy/whampyTableMixin.py", line 499, in click_map
    radius = radius)
  File "/home/fste075/anaconda3/envs/whampy_test/lib/python3.7/site-packages/whampy/clickMap.py", line 78, in __init__
    self.over_data = SpectralCube.read(over_data)
NameError: name 'SpectralCube' is not defined
```

I got it running by installing spectral cube separately but since whampy is pip installed this dependency can be taken care of on download. 

-----
*This issue is part of the current JOSS-review of whampy ( [#1940](https://github.com/openjournals/joss-reviews/issues/1940) )*

**Comment by Deech08** [comment]
I am modifying this tutorial to mention that the cartopy and spectral cube examples rely on those packages which are optional dependencies. I hope that this would prompt the user to manually install those packages as well if they want to run that part of the tutorial. I would prefer to leave both packages as optional dependencies, but can incorporate them in more directly if that is necessary.

**Comment by HeloiseS** [comment]
Sound fine to me! Would you mind making it very clear and explicit at the beginning of the tutorial that these need to be installed by the user? I know this may seem like overkill but I remember being new to python and people stating what was obvious to them would have tremendously helped me at times ;)

**Comment by Deech08** [comment]
I've adding additional text in both the readme and docs mentioning they need to be installed separately and with links to their documentation.
