### ISSUE TITLE
Moment Map not the same as tutorial - Very Minor 

### ISSUE THREAD

**Issue by HeloiseS** [Deech08/whampy#15]
## Issue
----

so I'm re-running the tutorial with the new pip version (0.2.0a2 and when doing the [moment map](https://whampy.readthedocs.io/en/latest/moment_maps.html) I got a **slightly** different result, see screenshot below (High vel regions at the top no longer there?).

![Screenshot from 2019-12-20 20-09-54](https://user-images.githubusercontent.com/15654896/71236979-32d96b00-2365-11ea-9135-e56c75bd70fa.png)

**Comment by Deech08** [comment]
Not entirely sure what the cause of this was, but I'm assuming there was some slight change to the data file I used to make the original map for the docs compared to the one i have up now. I updated the example image in the docs now.
