### ISSUE TITLE
[BUG] Minor issue with the docs

### ISSUE THREAD

**Issue by Gabriel-p** [Deech08/whampy#16]
**Describe the bug**
The code in the docs is cropped when the option to hide the `>>>` is used.

**To Reproduce**
Go to the docs (eg: https://whampy.readthedocs.io/en/latest/moment_maps.html) and click on the `>>>` box.

**Expected behavior**
The code show be fully displayed.

**Screenshots**
![Captura de pantalla de 2019-12-20 09-56-51](https://user-images.githubusercontent.com/6054951/71256686-44445800-2310-11ea-9196-8a17135a0759.png)
![Captura de pantalla de 2019-12-20 09-56-56](https://user-images.githubusercontent.com/6054951/71256687-44dcee80-2310-11ea-97c3-6e057e71133b.png)

**Comment by Deech08** [comment]
I didn't know that button to remove the >>> existed - that is super useful! Just made some changes so that the code lines don't disappear. Thanks for catching that!
