### ISSUE TITLE
Clear link to documentation

### ISSUE THREAD

**Issue by HeloiseS** [Deech08/whampy#4]
I struggled a little bit to find a link to your documentation in your README. 

The WHAM link under the badges is broken and I wonder if that wasn't meant to link to the docs (regardless you should update the broken link). 

I found [this](https://whampy.readthedocs.io/en/latest/?badge=latest#getting-started) by clicking the doc:passing badge (I'll go through it later). 

I think this deserves a link of it's own and a clear header in your README :)

-----
*This issue is part of the current JOSS-review of whampy ( [#1940](https://github.com/openjournals/joss-reviews/issues/1940) )*

**Comment by Deech08** [comment]
I've added a section after the Quick Start that links explicitly to the documentation. I was hoping users would just click on the doc:passing badge, but see that isn't super obvious. 

The broken WHAM link is also now fixed - it directs to a webpage on the instrument itself.
