### ISSUE TITLE
RuntimeWarning in QuickStart instructions

### ISSUE THREAD

**Issue by HeloiseS** [Deech08/whampy#5]
## Issue
Tried the quick start instructions after downloadig v0.2.0a1 and I get the following:
```
>>> moment_0, err_0 = survey.moment(order = 0, return_sigma = True)
/home/fste075/anaconda3/envs/whampy_test/lib/python3.7/site-packages/astropy/table/column.py:991: RuntimeWarning: invalid value encountered in less result = getattr(super(), op)(other)
```

The other two moments and errors calculate fine with no error :)

-----
*This issue is part of the current JOSS-review of whampy ( [#1940](https://github.com/openjournals/joss-reviews/issues/1940) )*

**Comment by Deech08** [comment]
I believe this happens because there are some nan values in the data. It should still compute fine, but just display the warning. Does the end result still give you actual numbers for moment_0 and err_0, or is there an actual error beyond the warning that stops it from executing?

**Comment by HeloiseS** [comment]
Ace, are these the values I should get?

```
>>> moment_0
<Quantity [0.94620246, 1.1443384 , 1.2161877 , ..., 6.932495  , 7.1546907 ,
           7.571975  ] R>
>>> err_0
<Quantity [0.23768413, 0.25891924, 0.27316484, ..., 0.3584447 , 0.2074711 ,
           0.38070837] R>
```

**Comment by Deech08** [comment]
Yes, those are the expected results!
