### ISSUE TITLE
[BUG] 'km2 / s2' printed to screen

### ISSUE THREAD

**Issue by Gabriel-p** [Deech08/whampy#7]
**Describe the bug**
A strange line is printed to screen.

**To Reproduce**
`$  moment_2, err_2 = survey.moment(order = 2, return_sigma = True)`

prints to screen:

`km2 / s2`

**Expected behavior**
Nothing?

**Additional context**
v 0.2.0a1

**Comment by Deech08** [comment]
will be fixed in next commit!
