### ISSUE TITLE
Perseus arm image does not match the on in the docs [BUG]

### ISSUE THREAD

**Issue by Gabriel-p** [Deech08/whampy#8]
**Describe the bug**
Documentation inconsistency

**To Reproduce**
Following the docs [here](https://whampy.readthedocs.io/en/latest/spiral_arms.html#making-spiral-arm-maps-with-whampy)

`>>> fig = perseus_arm.intensity_map(colorbar = True, s_factor = 2
                                   cbar_kwargs={"orientation":"horizontal"})`

Also, notice there's a `,` missing after `factor = 2`.

**Expected behavior**
Same image output as [the one displayed in the docs](https://whampy.readthedocs.io/en/latest/_images/perseus_arm_map.png).

**Screenshots**
This is what I get:

![Figure_1](https://user-images.githubusercontent.com/6054951/70864026-0c629c80-1f2d-11ea-9b3a-4e0d2669acff.png)

**Comment by HeloiseS** [comment]
Just to say I tested this and got the same result as @Gabriel-p - it doesn't seem to be an isolated problem.

**Comment by Deech08** [comment]
The get_spiral_slice method was missing a wrap_at_180 = True keyword to be set in the tutorial. Adding that fixes the problem. I've updated that in the docs and fixed the missing comma, which will be reflected in the next commit.  I will update this issue and close it after that commit is pushed.

**Comment by Deech08** [comment]
Actually - theres something else happening that i didn't notice. I will look into it and actually fix it soon!

**Comment by Deech08** [comment]
Issue actually arose from an updated lv-track file. I've addeed a lrange=[0,50] keyword to the get_spiral_slice example that gives a close match to the original image. I also updated the example image to show an exact reproduction. This will be live after my next commit in the future. once that commit is pushed i will close this issue.
